#!/bin/bash

filename="flags_test_help"
dir="$(mktemp -d)"
oldpwd="${PWD}"

cc -Wall -Wextra -Werror -o "${dir}/${filename}" \
     "${filename}.c" flags.c ../string/split.c

cd "${dir}"

if [[ -f ${filename} ]]; then
  "./${filename}"
  rm "${filename}"
fi
