#!/bin/bash

filename="flags_test_help"

cc -Wall -Wextra -Werror -o "${filename}" \
     "${filename}.c" flags.c ../string/split.c

if [[ -f ${filename} ]]; then
  "./${filename}"
  rm "${filename}"
fi
